language: python
python:
  - "2.7"

env:
  - DJANGO=1.5.5 TEST=testapp
  - DJANGO=1.6.2 TEST=testapp.tests

install:
  - pip install -q Django==$DJANGO --use-mirrors
  - python setup.py -q install
script: cd example/ && ./manage.py test $TEST
