language: python
python:
  - 2.7
  - 3.3

env:
  - DJANGO=1.5.6 TEST=testapp
  - DJANGO=1.6.3 TEST=testapp.tests

matrix:
  exclude:
    - python: 2.7
      env: DJANGO=1.5.6 TEST=testapp

install:
  - pip install -q Django==$DJANGO --use-mirrors
  - python setup.py -q install
script: cd example/ && ./manage.py test $TEST
