language: python
python:
  - "2.7"

env:
  - DJANGO=1.4.9
  - DJANGO=1.5.5
  - DJANGO=1.6

install:
  - pip install -q Django==$DJANGO --use-mirrors
  - python setup.py -q install
script: cd example/ && ./manage.py test testapp
