language: python
python:
  - 2.7
  - 3.3

env:
  - DJANGO=1.5.8
  - DJANGO=1.6.5

branches:
  only:
    - master

matrix:
  exclude:
  - python: 3.3
    env: DJANGO=1.5.8

install:
  - pip install -q Django==$DJANGO
  - python setup.py -q install

script:
  - cd example/ && ./manage.py test testapp --settings=testapp.settings
